name: ringoftrust_web
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: '>=0.2.2 <0.3.0'
  js: ^0.6.0
  material2_dart:
  dart_sass_transformer: any
  bootstrap:
  http: ^0.11.0
  stream_transformers: ^0.3.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- dart_sass_transformer
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter

